### ISSUE TITLE
Passing a message key to inline validator

### ISSUE THREAD

**Issue by goofiw** [jasonmit/ember-i18n-cp-validations#22]
It looks like passing a message key as an option to an inline validator does not override the default message.

I'm not sure if this is an issue, or perhaps there is a baked in way to achieve this functionality.

ex: 

``` js
addressResults: validator(function(value, options, model, attribute) {
  return model.get('addressResults')[0].partial_match ? this.createErrorMessage(options.messageKey, value, options) : true;
},
{
  messageKey: `errors.customMessages.addresResults.partialMatch`
})
```

**Comment by jasonmit** [comment]
In this case, you would likely want to omit `errors.` from the `messageKey` since it is implied if it goes through `createErrorMessage` since you really are providing `createErrorMessage` with the type of error which then is looked up under `errors.`

Let me know if that solves the issue before I start debugging.
